### ISSUE TITLE
front: U-004-自分の投稿一覧の「お気に入りShop」のリンクの確認

### ISSUE THREAD

**Issue by mei-omomo** [ccj7/coffee-clip#168]
mypageの95行目
/favorite-shopsを/user/favorite-shopsに変更する！

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201676789249169/1201733742862358) by [Unito](https://www.unito.io)

**Comment by Maho-Miyazawa** [comment]
- 解決済みのためcloseします
