### ISSUE TITLE
S-002 画像をアップロードしても変更できない

### ISSUE THREAD

**Issue by Motoki-tech** [ccj7/coffee-clip#189]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201676789249169/1201741262785416) by [Unito](https://www.unito.io)

**Comment by Motoki-tech** [comment]
変更を試みた後のダッシュボード画面

<img width="505" alt="スクリーンショット 2022-01-31 14 09 35" src="https://user-images.githubusercontent.com/81059230/151742023-dc54710a-ee9c-417f-8591-4f18138b3020.png">

**Comment by Maho-Miyazawa** [comment]
- envファイルの設定ミスが原因
- 解消したためissueをclose
