### ISSUE TITLE
Shop S-004 店舗ページを確認 リンク切れしているので確認

### ISSUE THREAD

**Issue by mahomiyata** [ccj7/coffee-clip#200]
![image](https://user-images.githubusercontent.com/90583764/151744672-ae26d62f-ce35-4432-a70a-50d20a734ae2.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201676789249169/1201741319689317) by [Unito](https://www.unito.io)

**Comment by mahomiyata** [comment]
治ったかも……？

**Comment by Maho-Miyazawa** [comment]
- 画像がない場合にimgタグを削除したことで対応
