### ISSUE TITLE
U-signup 何文字以上などの表記、アクションをした後の表示

### ISSUE THREAD

**Issue by mei-omomo** [ccj7/coffee-clip#201]
■ユーザーのサインアップ画面
http://ec2-52-199-216-63.ap-northeast-1.compute.amazonaws.com/user/signup

・「ユーザーネームは何文字以上」や「必須」などの表記があるといいかも
・アイコン画像を選択しないでsubmit押したけど何も起きない、そしてアイコン画像を選択してsubmit押しても何も起きない
→何かしらの表示を出した方が親切かも・・・！

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201676789249169/1201741234211348) by [Unito](https://www.unito.io)

**Comment by Maho-Miyazawa** [comment]
- 解決済みのためclose
