### ISSUE TITLE
front: 画像がない場合はimageタグを表示しない

### ISSUE THREAD

**Issue by mahomiyata** [ccj7/coffee-clip#206]
![image](https://user-images.githubusercontent.com/90583764/151746273-96d03ba7-5ed5-43f1-9cf2-6d221dd02c2d.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201676789249169/1201741381329463) by [Unito](https://www.unito.io)

**Comment by Maho-Miyazawa** [comment]
Paddyが完了したのでcloseします〜！
