### ISSUE TITLE
S-002 & S-004からS-001に戻れるルートがほしい

### ISSUE THREAD

**Issue by Maho-Miyazawa** [ccj7/coffee-clip#248]
* S-002のページや、S-004のページに飛んだ後に、ダッシュボードに戻る導線がないので、どこかに導線があると嬉しい
  * S-002や、S-004のページにあるのがベストですが、難しければHeaderなどでも？
* 現状は、ブラウザ自身の戻るボタンでダッシュボードに戻ることができる

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201676789249169/1201755386297682) by [Unito](https://www.unito.io)

**Comment by mahomiyata** [comment]
https://github.com/ccj7/coffee-clip/pull/263
