### ISSUE TITLE
U-007 新規ログ作成後の挙動修正

### ISSUE THREAD

**Issue by Maho-Miyazawa** [ccj7/coffee-clip#260]
* 現状
  * 「投稿」ボタンを押すと、「保存しました」の文字が表示される
  * フォームには入力した内容が残り続けている
  * POSTはきちんと行われている
* 修正例
  * 例1）新規投稿が成功した場合、フォームの中身を空にし、続けて別の投稿ができるようにする
  * 例2）タイムライン or マイページに、リダイレクトさせる

![image](https://user-images.githubusercontent.com/61673527/152136948-f1eda54f-a2cd-48f6-a898-6ae6453a5683.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201676789249169/1201756700375445) by [Unito](https://www.unito.io)

**Comment by naonmr** [comment]
POST後、フォームを消す＆メッセージとボタンを表示

**Comment by naonmr** [comment]
text = 新規ログを投稿しました
に変更
