### ISSUE TITLE
【User】setting画面の保存とキャンセルボタンの位置ずれ

### ISSUE THREAD

**Issue by Motoki-tech** [ccj7/coffee-clip#291]
![](https://user-images.githubusercontent.com/81059230/152292071-eb175a77-7041-4333-b4c3-5115fec456ba.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201676789249169/1201761898747467) by [Unito](https://www.unito.io)

**Comment by mahomiyata** [comment]
@Motoki-tech 修正ずみです！
![image](https://user-images.githubusercontent.com/90583764/152324872-032703ba-fccf-4558-b2a4-9360539ec2a0.png)
