### ISSUE TITLE
Front: ファビコン変更

### ISSUE THREAD

**Issue by Maho-Miyazawa** [ccj7/coffee-clip#321]
* 現在Next.jsのデフォルトのファビコンのため、変更する

![image](https://user-images.githubusercontent.com/61673527/152329297-2a641b24-f853-4952-9b92-6c285d015cbf.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201676789249169/1201763381409279) by [Unito](https://www.unito.io)

**Comment by naonmr** [comment]
#345
めいさんロゴでき次第対応
