### ISSUE TITLE
U-002 / U-005: shop画像の縦の長さの上限設定

### ISSUE THREAD

**Issue by Maho-Miyazawa** [ccj7/coffee-clip#341]
* 縦長の画像の場合、他と比べてレイアウトが縦長になっている印象があるため、サイズがある程度一定になっていた方が良いかも？

![image](https://user-images.githubusercontent.com/61673527/152385172-c84e6cd9-ea8b-46d1-bb92-f6934d739312.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201676789249169/1201765349940762) by [Unito](https://www.unito.io)

**Comment by mei-omomo** [comment]
優先度高いラベルつけたけど見てから判断

**Comment by naonmr** [comment]
shopCardのみ未対応
