### ISSUE TITLE
U-008 / S-004: コンセプトの辺りまでスクロールするとHeaderが消えてしまう

### ISSUE THREAD

**Issue by Maho-Miyazawa** [ccj7/coffee-clip#344]
- U-008、S-004のどちらも同じく途中でHeaderが消えてしまう

![image](https://user-images.githubusercontent.com/61673527/152388176-4a4c3769-25a6-4d93-a876-d44b4c1c2389.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201676789249169/1201765649071240) by [Unito](https://www.unito.io)

**Comment by mei-omomo** [comment]
「優先度高い」ラベルを付けたけど、見てみないとわからないので見てみてから判断したい！
